---
# Configuration for the LDAP directory where user objects are held
idstore:
    # IP address of the LDAP server
    address: 127.0.0.1

    # TCP port for the LDAP service
    port: 389

    # The service requires a low privileged (read only, search) service account to
    #  conduct an initial query against the directory upon user authentication

    # DN for the service account used to conduct user searches
    serviceaccountdn: 'cn=admin,dc=hd,dc=local'

    # Password for the service account used to conduct user searches
    serviceaccountpassword: 'Password1'


    # DN for the base OU under which all user objects are stored.  This will be used
    #  as the root for a search each time a user logs in
    basesearchdn: 'dc=hd,dc=local'


# List of attributes that need to be read for the user object and added to the claim as
#  part of the JW token passed to the consuming application
attributes:
    claims:
        sn: family_name
        givenName: given_name
        mail: email
        employeeNumber: id_number

