---
  directory:
    dn: CN=Users,DC=hd,DC=local
    fqdn: hd.local

  frontend:
    address: https://10.211.55.2:5000

  sms:
    message: "A reset code has been requested for your account.\n\nIf this was in error contact the service desk on 0113 235 3315.\n\nYour reset code is %s"
    organisation_shortname: RothICT
    twilio_sid: ACf5e81dd572ad916b9dbd6d1883e755ae
    twilio_authcode: b3ae4c2f616c9f9529aba41ce219cfd6

  redis:
    address: 127.0.0.1
    port: 6379
    db: 0


