---
  directory:
    dn: DC=hd,DC=local
    fqdn: hippo.digital

  frontend:
    address: http://10.211.55.2:5002

  auth_service:
    address: https://gas.nis1.national.ncrs.nhs.uk
    #http://10.211.55.2:5000

#  directory:
#    dn: OU=Departments,DC=xRothGen,DC=nhs,DC=uk
#    fqdn: xRothGen.nhs.uk
#
#  frontend:
#    address: https://pwd.hippo.digital:444

  sms:
    message: "A reset code has been requested for your account.\n\nIf this was in error contact the service desk on extension 8844.\n\nYour reset code is %s"
    organisation_shortname: "441466455031"
    twilio_sid: ACf5e81dd572ad916b9dbd6d1883e755ae
    twilio_authcode: b3ae4c2f616c9f9529aba41ce219cfd6

  redis:
    address: 127.0.0.1
    port: 6379
    db: 0


  private_key: >
    MIIEogIBAAKCAQEApaaE3Bu5pBEbFQ67rXzvrwwya7VKfPyF6gxw4s/FSmuO2olq
    vmHpxOLvOvY5YsAjARM1oI0PZ4dv4OsTpHsCTw/v5tbcaYw4VZnAwmZKsna8NuP7
    yKgHOR1J2Iql07NLpIR436Imp9TvlFB2pWRpS3cmg0rJcO7r3BkajrnAv9qppqnX
    w9ZCYS1J8UEoOUN42/8pKyRboTZ7PPCwb3eGIOdi8hSH65zJhv+n+2zoLSwMLGt0
    w4v5Ami21tB5izyxl4MYY1hO93UT1UBXcceAoNAVu8TWDBLKUhVk+cL3TMk8eYCM
    8LQCLMqveCdGEJ4J8rHop/lFVqA2OLItvb/zjQIDAQABAoIBAGcKI86+uEUkFtKM
    bZXHB1i9n4d8J6+DbNFfl8CeOTzHlv69R9bRFRbRiroEe0G//oYmqs8Jr7FYf/FK
    iNdhZNhFM5dFw6kr/cbRcyP5eTF1xjHmsrHoQ0X1v/+gjvIWr1DQzlddh+oR/E0n
    mAXdZdn5bc1xcch79d7dBrYNOaacnxIeazEEBpfyq0fV0IUlyOYik1X9UTQlmO1g
    lLEQAcf6ydovXgXcgHaBLeKiBJnTv1M7tFVnKf3fjYeoglxbYKPQSw7neGVJVpjG
    CbTLlmmwkODCLlPaPi4munuDQxKkSMgJ5cKZQU61H15EWTH8DK+VD5jhlm2TzxoE
    W1ceegkCgYEA2onrtkCttnmI8FPwhRviQcUUqnW+PGyalcosg7vP1DjhtDPoYOJC
    Ka0XuYUPJ67QMfZqD+nSQG6tu0r6uTQFWlaGi09UDuJOt7QvbAeYiYU5ibHsg12r
    FSU/N5eao3m5zlfXspRACUbBhozJfjYLpwvAWdLobsdCYQc/TaQdOjsCgYEAwgu3
    GhfeG9/Y4PCXDlQ817aZwNsZMANyNGDo6SJMu924R4+BnlTVTa5DlpKABN5PoygV
    RAnExvN/1Mexd4Pt+YCbZeKUQwRL837RlD8oummNHH1FyN2metV3lnrNBCw8lc4L
    /HtuTvtFa3agsD1oO4SUS92PpJ2+42Lvvu8PZNcCgYBU4p2b/SN8bVizgOc7zMjl
    oxeT3og2EDk7VXxU7u6bED0bMc5hU4E/juxYM0bfsxdLUNuBsuDoBhWVWlpo9bve
    ix1Xn0iXP3A0CtkgrRKi2AyxX1ru68M4Q296uHhoZy+05onx44O8Fq+1A5qAW53L
    FNVyDmoaHWu7JIWCMuznYQKBgGNhlqSBhtrl2XDTJ7pKAGNGfRad4BeMHEihPYhx
    bbVmCAR2hh8uOZSwZKNQYsqbhVP9qm6PRj3S5ix3HfglFJONf4k980sjfza1Q+dW
    NajLeF8X9c67XpFYlQf32tqBQYJD5jWojcVbwaEZP5Ej0idxbnYwgmn/9I0G1d0H
    GO4/AoGAbJpDhD7Rjn3tMQDVyqdKU7+7KhkGMwMMh1nzOYeUC75sDfBXpVKveXVy
    hZuRK6SD9lV4MFl+1H1igBqHVUj5t2zTqNDAxoh13HqpxxxH4GIn0SWbZBNbLfcO
    KjiITfQGNThfsTh2/1HPl6A61E4Iw2G+xGXuy0O/IvYvwBNwveE=
